version: "3.9"
services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest # gis-ops/docker-valhalla image.
    container_name: valhalla_gis-ops # The name of the container.
    ports:
      - 8002:8002
    deploy:
      resources:
        limits:
          memory: 16g
    volumes:
      - ./custom_files/:/custom_files # The location where all data will be stored.
    environment:
      - tile_urls=http://download.geofabrik.de/europe/slovakia-latest.osm.pbf # The location of the trajectories you want to be map matched.
      #- server_threads=1 # Determines how many threads will be used to run the valhalla server.
      #- serve_tiles=True # If True, starts the service. If false, stops after building the graph.
      #- use_tiles_ignore_pbf=True # Load existing valhalla_tiles.tar directly.
      #- tileset_name=valhalla_tiles # Name of the resulting graph on disk.
      #- build_elevation=False # Build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles.
      #- build_admins=False # Build admins db with "True" or "Force".
      #- build_time_zones=False # Build timezone db with "True" or "Force".
      #- build_tar=True # Build an indexed tar file from the tile_dir for faster graph loading times.
      #- force_rebuild=False # Forces a rebuild of the routing tiles with "True".
